export const LOAD_TILE = 'LOAD_TILE';
export const LOAD_TILES = 'LOAD_TILES';
export const SET_TILE_ANIMATION = 'SET_TILE_ANIMATION';
export const CLEAR_TILE_ANIMATION = 'CLEAR_TILE_ANIMATION';
export const DELETE_TILE = 'DELETE_TILE';
export const REORDER_TILE = 'REORDER_TILE';

export const CREATE_BLOCK = 'CREATE_BLOCK';
export const MODIFY_BLOCK = 'MODIFY_BLOCK';
export const DELETE_BLOCK = 'DELETE_BLOCK';


