export const ADD_TILE = 'ADD_TILE';
export const MOVE_TILE = 'MOVE_TILE';
export const SET_TILE_ANIMATION = 'SET_TILE_ANIMATION';
export const CLEAR_TILE_ANIMATION = 'CLEAR_TILE_ANIMATION';
export const DELETE_TILE = 'DELETE_TILE';

export const DEFINE_BLOCK = 'DEFINE_BLOCK';
export const SET_BLOCK_PREVIEW = 'SET_BLOCK_PREVIEW';
