require('./objectExtenderTest');
require('./ReactorTest');
require('./TranslatorTest');
require('./AnimationTest');
require('./SchedulerTest');
require('./DoorContextTest');
require('./LocationTest');
require('./ColliderTest');
require('./GridTest');
