export const ADD_QUEST_ITEM = 'ADD_QUEST_ITEM';
export const REMOVE_QUEST_ITEM = 'REMOVE_QUEST_ITEM';
export const DEFINE_ITEMS = 'DEFINE_ITEMS';

export const SET_PLAYER_HP = 'SET_PLAYER_HP';
export const MODIFY_PLAYER_HP = 'MODIFY_PLAYER_HP';
export const SET_PLAYER_MAX_HP = 'SET_PLAYER_MAX_HP';

export const INC_ENERGY = 'INC_ENERGY';
export const DEC_ENERGY = 'DEC_ENERGY';
export const DEPLETE_ENERGY = 'DEPLETE_ENERGY';
export const SHOOT = 'SHOOT';
export const AIMING_SUPERNATURAL = 'AIMING_SUPERNATURAL';
export const SET_CAMERA_LAMP = 'SET_CAMERA_LAMP';
export const SET_CAMERA_WIDTH = 'SET_CAMERA_WIDTH';

export const ADD_SUPERNATURAL_BEACON = 'ADD_SUPERNATURAL_BEACON';

