export const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';
export const REMOVE_INVENTORY_ITEM = 'REMOVE_INVENTORY_ITEM';
export const DEFINE_ITEMS = 'DEFINE_ITEMS';

export const SET_PLAYER_HP = 'SET_PLAYER_HP';
export const MODIFY_PLAYER_HP = 'MODIFY_PLAYER_HP';
export const SET_PLAYER_MAX_HP = 'SET_PLAYER_MAX_HP';

export const SET_STATE_CONTENT = 'SET_STATE_CONTENT';

export const INC_SCORE = 'INC_SCORE'
