export const ADD_QUEST_ITEM = 'ADD_QUEST_ITEM';
export const REMOVE_QUEST_ITEM = 'REMOVE_QUEST_ITEM';
export const DEFINE_ITEMS = 'DEFINE_ITEMS';

export const SET_PLAYER_HP = 'SET_PLAYER_HP';
export const SET_PLAYER_MAX_HP = 'SET_PLAYER_MAX_HP';