export const LOAD_TILE = 'LOAD_TILE';
export const LOAD_TILES = 'LOAD_TILES';
export const SET_TILE_ANIMATION = 'SET_TILE_ANIMATION';
export const CLEAR_TILE_ANIMATION = 'CLEAR_TILE_ANIMATION';
export const DELETE_TILE = 'DELETE_TILE';
export const REORDER_TILE = 'REORDER_TILE';

export const CREATE_BLOCK = 'CREATE_BLOCK';
export const MODIFY_BLOCK = 'MODIFY_BLOCK';
export const DELETE_BLOCK = 'DELETE_BLOCK';

export const CREATE_THING = 'CREATE_THING';
export const MODIFY_THING = 'MODIFY_THING';
export const DELETE_THING = 'DELETE_THING';
export const REORDER_THING = 'REORDER_THING';

export const SET_GRID_SIZE = 'SET_GRID_SIZE';

export const SET_CELL_PROPS = 'SET_CELL_PROPS';
export const ADD_CELL_TAG = 'ADD_CELL_TAG';
export const REMOVE_CELL_TAG = 'REMOVE_CELL_TAG';
export const MODIFY_CELL_TAG = 'MODIFY_CELL_TAG';
export const SET_CELL_MARK = 'SET_CELL_MARK';
export const SET_GRID_CELL = 'SET_GRID_CELL';
export const SET_GRID_CELLS = 'SET_GRID_CELLS';
export const REMOVE_CELL_THING = 'REMOVE_CELL_THING';


export const LOAD_LEVEL = 'LOAD_LEVEL';

export const SETUP_AMBIANCE = 'SETUP_AMBIANCE';
export const SET_FLAG = 'SET_FLAG';
export const SET_TILE_WIDTH = 'SET_TILE_WIDTH';
export const SET_TILE_HEIGHT = 'SET_TILE_HEIGHT';
export const SET_PREVIEW = 'SET_PREVIEW';
export const REPLACE_TILE_CONTENT = 'REPLACE_TILE_CONTENT';
export const FEEDBACK_TILE_WIDTH = 'FEEDBACK_TILE_WIDTH';


export const SET_STARTING_POINT = 'SET_STARTING_POINT';
export const SHIFT_GRID = 'SHIFT_GRID';
export const SET_CAMERA_THINKER = 'SET_CAMERA_THINKER';

