export const ADD_TILE = 'ADD_TILE';
export const MOVE_TILE = 'MOVE_TILE';
export const SET_TILE_ANIMATION = 'SET_TILE_ANIMATION';
export const CLEAR_TILE_ANIMATION = 'CLEAR_TILE_ANIMATION';
export const DELETE_TILE = 'DELETE_TILE';

export const DEFINE_BLOCK = 'DEFINE_BLOCK';
export const SET_BLOCK_PREVIEW = 'SET_BLOCK_PREVIEW';
export const DESTROY_BLOCK = 'DESTROY_BLOCK';

export const DEFINE_THING = 'DEFINE_THING';
export const DESTROY_THING = 'DESTROY_THING';
export const MOVE_THING = 'MOVE_THING';

export const SET_GRID_SIZE = 'SET_GRID_SIZE';
export const SET_CELL_BLOCK = 'SET_CELL_BLOCK';
export const SET_CELL_TAGS = 'SET_CELL_TAGS';
export const ADD_CELL_TAG = 'ADD_CELL_TAG';
export const REMOVE_CELL_TAG = 'REMOVE_CELL_TAG';
export const MODIFY_CELL_TAG = 'MODIFY_CELL_TAG';
export const SET_CELL_MARK = 'SET_CELL_MARK';
export const SET_CELL_THING = 'SET_CELL_THING';
export const SET_CELL_UPPER_BLOCK = 'SET_CELL_UPPER_BLOCK';
export const REMOVE_CELL_THING = 'REMOVE_CELL_THING';

export const SETUP_AMBIANCE = 'SETUP_AMBIANCE';


export const SET_STATE_CONTENT = 'SET_STATE_CONTENT';

export const SET_FLAG_SMOOTH = 'SET_FLAG_SMOOTH';
export const SET_FLAG_STRETCH = 'SET_FLAG_STRETCH';
export const SET_FLAG_EXPORT = 'SET_FLAG_EXPORT';
export const SET_TILE_WIDTH = 'SET_TILE_WIDTH';
export const SET_TILE_HEIGHT = 'SET_TILE_HEIGHT';

export const SET_PREVIEW = 'SET_PREVIEW';

export const REPLACE_TILE_CONTENT = 'REPLACE_TILE_CONTENT';
export const REPLACE_BLOCK_OFFSET = 'REPLACE_BLOCK_OFFSET';

export const SET_STARTING_POINT = 'SET_STARTING_POINT';

export const SHIFT_GRID = 'SHIFT_GRID';

export const SET_CAMERA_THINKER = 'SET_CAMERA_THINKER';
