export const LIST_LEVELS = 'LIST_LEVELS';
export const SET_STATUSBAR_TEXT = 'SET_STATUSBAR_TEXT';
export const SELECT_REGION = 'SELECT_REGION';
export const POP_UNDO = 'POP_UNDO';
export const SET_LEVEL_NAME = 'SET_LEVEL_NAME';
export const SET_SELECTED_TOOL = 'SET_SELECTED_TOOL';
