
// BLOCK BUILDER
export const SELECT_REGION = 'SELECT_REGION';

export const BLOCKBROWSER_SET_SELECTED = 'BLOCKBROWSER_SET_SELECTED';
export const THINGBROWSER_SET_SELECTED = 'THINGBROWSER_SET_SELECTED';
export const LEVELGRID_THING_SET_SELECTED = 'LEVELGRID_THING_SET_SELECTED';
export const TILEBROWSER_SET_TILE_TYPE = 'TILEBROWSER_SET_TILE_TYPE';
export const SOMETHING_HAS_CHANGED = 'SOMETHING_HAS_CHANGED';
export const SET_LEVEL_LIST = 'SET_LEVEL_LIST';
export const SET_LEVEL_NAME = 'SET_LEVEL_NAME';
export const SET_STATUSBAR_TEXT = 'SET_STATUSBAR_TEXT';
export const PUSH_UNDO = 'PUSH_UNDO';
export const POP_UNDO = 'POP_UNDO';
export const SET_HIGHLIGHTED_TAGS = 'SET_HIGHLIGHTED_TAGS';
export const REMOVE_HIGHLIGHTED_TAG = 'REMOVE_HIGHLIGHTED_TAG';
export const ADD_HIGHLIGHTED_TAG = 'ADD_HIGHLIGHTED_TAG';
export const SET_LEVEL_GENERATED_DATA = 'SET_LEVEL_GENERATED_DATA';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';
export const SET_POPUP_TYPE = 'SET_POPUP_TYPE';
export const SET_POPUP_CONTENT = 'SET_POPUP_CONTENT';
export const SET_POPUP_PROGRESS = 'SET_POPUP_PROGRESS';

export const SET_SELECTED_TOOL = 'SET_SELECTED_TOOL';

export const SET_USER = 'SET_USER';
