
// BLOCK BUILDER
export const BLOCKBUILDER_SET_ID = 'BLOCKBUILDER_SET_ID';
export const BLOCKBUILDER_SET_REF = 'BLOCKBUILDER_SET_REF';
export const BLOCKBUILDER_SET_PHYS = 'BLOCKBUILDER_SET_PHYS';
export const BLOCKBUILDER_SET_OFFS = 'BLOCKBUILDER_SET_OFFS';
export const BLOCKBUILDER_SET_LIGHT = 'BLOCKBUILDER_SET_LIGHT';
export const BLOCKBUILDER_SET_LIGHT_VALUE = 'BLOCKBUILDER_SET_LIGHT_VALUE';
export const BLOCKBUILDER_SET_LIGHT_INNER_RADIUS = 'BLOCKBUILDER_SET_LIGHT_INNER_RADIUS';
export const BLOCKBUILDER_SET_LIGHT_OUTER_RADIUS = 'BLOCKBUILDER_SET_LIGHT_OUTER_RADIUS';
export const BLOCKBUILDER_SET_FACE = 'BLOCKBUILDER_SET_FACE';
export const BLOCKBUILDER_SET_FACE_NORTH = 'BLOCKBUILDER_SET_FACE_NORTH';
export const BLOCKBUILDER_SET_FACE_EAST = 'BLOCKBUILDER_SET_FACE_EAST';
export const BLOCKBUILDER_SET_FACE_WEST = 'BLOCKBUILDER_SET_FACE_WEST';
export const BLOCKBUILDER_SET_FACE_SOUTH = 'BLOCKBUILDER_SET_FACE_SOUTH';
export const BLOCKBUILDER_SET_FACE_FLOOR = 'BLOCKBUILDER_SET_FACE_FLOOR';
export const BLOCKBUILDER_SET_FACE_CEILING = 'BLOCKBUILDER_SET_FACE_CEILING';

export const ANIMBUILDER_SET_START = 'ANIMBUILDER_SET_START';
export const ANIMBUILDER_SET_FRAMES = 'ANIMBUILDER_SET_FRAMES';
export const ANIMBUILDER_SET_DURATION = 'ANIMBUILDER_SET_DURATION';
export const ANIMBUILDER_SET_LOOP = 'ANIMBUILDER_SET_LOOP';

export const SELECT_REGION = 'SELECT_REGION';

export const SET_LEVEL_LIST = 'SET_LEVEL_LIST';
export const SET_STATUSBAR_TEXT = 'SET_STATUSBAR_TEXT';

