
// BLOCK BUILDER
export const BLOCKBUILDER_SET_PHYS = 'BLOCKBUILDER_SET_PHYS';
export const BLOCKBUILDER_SET_OFFS = 'BLOCKBUILDER_SET_OFFS';
export const BLOCKBUILDER_SET_ANIM = 'BLOCKBUILDER_SET_ANIM';
export const BLOCKBUILDER_SET_ANIM_FRAMES = 'BLOCKBUILDER_SET_ANIM_FRAMES';
export const BLOCKBUILDER_SET_ANIM_DURATION = 'BLOCKBUILDER_SET_ANIM_DURATION';
export const BLOCKBUILDER_SET_ANIM_LOOP = 'BLOCKBUILDER_SET_ANIM_LOOP';
export const BLOCKBUILDER_SET_LIGHT = 'BLOCKBUILDER_SET_LIGHT';
export const BLOCKBUILDER_SET_LIGHT_VALUE = 'BLOCKBUILDER_SET_LIGHT_VALUE';
export const BLOCKBUILDER_SET_LIGHT_INNER_RADIUS = 'BLOCKBUILDER_SET_LIGHT_INNER_RADIUS';
export const BLOCKBUILDER_SET_LIGHT_OUTER_RADIUS = 'BLOCKBUILDER_SET_LIGHT_OUTER_RADIUS';
export const BLOCKBUILDER_SET_FACE = 'BLOCKBUILDER_SET_FACE';
export const BLOCKBUILDER_SET_FACE_NORTH = 'BLOCKBUILDER_SET_FACE_NORTH';
export const BLOCKBUILDER_SET_FACE_EAST = 'BLOCKBUILDER_SET_FACE_EAST';
export const BLOCKBUILDER_SET_FACE_WEST = 'BLOCKBUILDER_SET_FACE_WEST';
export const BLOCKBUILDER_SET_FACE_SOUTH = 'BLOCKBUILDER_SET_FACE_SOUTH';
export const BLOCKBUILDER_SET_FACE_FLOOR = 'BLOCKBUILDER_SET_FACE_FLOOR';
export const BLOCKBUILDER_SET_FACE_CEILING = 'BLOCKBUILDER_SET_FACE_CEILING';



