export const INC_ENERGY = 'INC_ENERGY';
export const DEC_ENERGY = 'DEC_ENERGY';
export const DEPLETE_ENERGY = 'DEPLETE_ENERGY';
export const SET_SHOOT_LAST_TIME = 'SHOOT';
export const AIMING_SUPERNATURAL = 'AIMING_SUPERNATURAL';
export const SET_CAMERA_LAMP = 'SET_CAMERA_LAMP';
export const SET_CAMERA_WIDTH = 'SET_CAMERA_WIDTH';